const std = @import("std");

const src_dir = "src/atlas/";

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const atlas_lib = b.addStaticLibrary(.{
        .name = "atlas",
        .target = target,
        .optimize = optimize,
    });
    atlas_lib.linkLibCpp();
    atlas_lib.addCSourceFiles(c_files, &.{""});

    const git_sha1H = b.addConfigHeader(.{
        .include_path = src_dir ++ "library/git_sha1.h",
        .style = .blank,
    }, .{
        .ATLAS_GIT_SHA1 = "",
    });
    const versionH = b.addConfigHeader(.{
        .include_path = src_dir ++ "library/version.h",
        .style = .blank,
    }, .{
        .atlas_VERSION_STR = "",
        .atlas_VERSION = "",
        .atlas_VERSION_MAJOR = "",
        .atlas_VERSION_MINOR = "",
        .atlas_VERSION_PATCH = "",
    });
    const conf = b.addConfigHeader(.{
        .include_path = src_dir ++ "library/library.h",
        .style = .blank,
    }, .{
        .ATLAS_HAVE_OMP = true,
        .ATLAS_OMP_TASK_SUPPORTED = true,
        .ATLAS_OMP_TASK_UNTIED_SUPPORTED = true,
        .ATLAS_HAVE_ACC = true,
        .ATLAS_HAVE_QHULL = true,
        .ATLAS_HAVE_CGAL = true,
        .ATLAS_HAVE_TESSELATION = true,
        .ATLAS_HAVE_FORTRAN = true,
        .ATLAS_HAVE_EIGEN = true,
        .ATLAS_HAVE_FFTW = true,
        .ATLAS_HAVE_MPI = true,
        .ATLAS_HAVE_PROJ = true,
        .ATLAS_BITS_GLOBAL = true,
        .ATLAS_ARRAYVIEW_BOUNDS_CHECKING = true,
        .ATLAS_INDEXVIEW_BOUNDS_CHECKING = true,
        .ATLAS_VECTOR_BOUNDS_CHECKING = true,
        .ATLAS_INIT_SNAN = true,
        .ATLAS_HAVE_GRIDTOOLS_STORAGE = true,
        .ATLAS_GRIDTOOLS_STORAGE_BACKEND_HOST = true,
        .ATLAS_GRIDTOOLS_STORAGE_BACKEND_CUDA = true,
        .ATLAS_HAVE_TRANS = true,
        .ATLAS_HAVE_ECTRANS = true,
        .ATLAS_HAVE_FEENABLEEXCEPT = true,
        .ATLAS_HAVE_FEDISABLEEXCEPT = true,
        .ATLAS_BUILD_TYPE_DEBUG = true,
        .ATLAS_BUILD_TYPE_RELEASE = true,
        .ATLAS_ECKIT_VERSION_INT = true,
        .ATLAS_ECKIT_DEVELOP = true,
        .ATLAS_HAVE_FUNCTIONSPACE = true,
        .ATLAS_HOST_DEVICE = "",
        .ATLAS_DEVICE = "",
        .ATLAS_HOST = "",
        .ATLAS_BITS_LOCAL = "",
    });

    atlas_lib.addConfigHeader(conf);
    atlas_lib.addConfigHeader(git_sha1H);
    atlas_lib.addConfigHeader(versionH);

    inline for (include_paths) |p|
        atlas_lib.addIncludePath(.{ .path = src_dir ++ p });

    atlas_lib.addIncludePath(.{ .path = src_dir });
    atlas_lib.addIncludePath(.{ .path = "src" });

    b.installArtifact(atlas_lib);
}

const include_paths = &.{
    "",
    "array",
    "array/gridtools",
    "array/helpers",
    "array/native",
    "domain",
    "domain/detail",
    "field",
    "field/detail",
    "functionspace",
    "functionspace/detail",
    "grid",
    "grid/detail/distribution",
    "grid/detail/grid",
    "grid/detail/partitioner",
    "grid/detail/pl/classic_gaussian",
    "grid/detail/spacing",
    "grid/detail/spacing/gaussian",
    "grid/detail/tiles",
    "grid/detail/vertical",
    "interpolation",
    "interpolation/element",
    "interpolation/method",
    "interpolation/method/cubedsphere",
    "interpolation/method/knn",
    "interpolation/method/sphericalvector",
    "interpolation/method/structured",
    "interpolation/method/structured/kernels",
    "interpolation/method/unstructured",
    "interpolation/nonlinear",
    "io",
    "library",
    "library/detail",
    "linalg",
    "linalg/dense",
    "linalg/sparse",
    "mesh",
    "mesh/actions",
    "mesh/detail",
    "mesh/elementtypes",
    "meshgenerator",
    "meshgenerator/detail",
    "meshgenerator/detail/cubedsphere",
    "numerics",
    "numerics/fvm",
    "option",
    "output",
    "output/detail",
    "parallel",
    "parallel/mpi",
    "parallel/omp",
    "projection",
    "projection/detail",
    "redistribution",
    "redistribution/detail",
    "runtime",
    "runtime/trace",
    "trans",
    "trans/detail",
    "trans/ifs",
    "trans/local",
    "util",
    "util/detail",
    "util/function",
};

const c_files = &.{
    src_dir ++ "mesh/Nodes.cc",
    src_dir ++ "mesh/ElementType.cc",
    src_dir ++ "mesh/HybridElements.cc",
    src_dir ++ "mesh/Halo.cc",
    src_dir ++ "mesh/detail/PartitionGraph.cc",
    src_dir ++ "mesh/detail/MeshIntf.cc",
    src_dir ++ "mesh/detail/MeshImpl.cc",
    src_dir ++ "mesh/detail/MeshBuilderIntf.cc",
    src_dir ++ "mesh/detail/AccumulateFacets.cc",
    src_dir ++ "mesh/Elements.cc",
    src_dir ++ "mesh/Mesh.cc",
    src_dir ++ "mesh/MeshBuilder.cc",
    src_dir ++ "mesh/actions/ExtendNodesGlobal.cc",
    src_dir ++ "mesh/actions/BuildNode2CellConnectivity.cc",
    src_dir ++ "mesh/actions/ReorderHilbert.cc",
    src_dir ++ "mesh/actions/BuildCellCentres.cc",
    src_dir ++ "mesh/actions/BuildStatistics.cc",
    src_dir ++ "mesh/actions/Reorder.cc",
    src_dir ++ "mesh/actions/BuildEdges.cc",
    src_dir ++ "mesh/actions/BuildHalo.cc",
    src_dir ++ "mesh/actions/BuildPeriodicBoundaries.cc",
    src_dir ++ "mesh/actions/BuildParallelFields.cc",
    src_dir ++ "mesh/actions/BuildXYZField.cc",
    src_dir ++ "mesh/actions/Build2DCellCentres.cc",
    src_dir ++ "mesh/actions/BuildTorusXYZField.cc",
    src_dir ++ "mesh/actions/BuildConvexHull3D.cc",
    src_dir ++ "mesh/actions/ReorderReverseCuthillMckee.cc",
    src_dir ++ "mesh/actions/BuildDualMesh.cc",
    src_dir ++ "mesh/actions/WriteLoadBalanceReport.cc",
    src_dir ++ "mesh/Connectivity.cc",
    src_dir ++ "mesh/PartitionPolygon.cc",
    src_dir ++ "redistribution/detail/RedistributionImpl.cc",
    src_dir ++ "redistribution/detail/RedistributionInterface.cc",
    src_dir ++ "redistribution/detail/RedistributeStructuredColumns.cc",
    src_dir ++ "redistribution/detail/RedistributeGeneric.cc",
    src_dir ++ "redistribution/detail/RedistributionImplFactory.cc",
    src_dir ++ "redistribution/Redistribution.cc",
    src_dir ++ "parallel/HaloExchange.cc",
    src_dir ++ "parallel/mpi/mpi.cc",
    src_dir ++ "parallel/omp/omp.cc",
    src_dir ++ "parallel/GatherScatter.cc",
    src_dir ++ "parallel/Checksum.cc",
    src_dir ++ "linalg/dense/MatrixMultiply_EckitLinalg.cc",
    src_dir ++ "linalg/dense/Backend.cc",
    src_dir ++ "linalg/sparse/SparseMatrixMultiply_EckitLinalg.cc",
    src_dir ++ "linalg/sparse/SparseMatrixMultiply_OpenMP.cc",
    src_dir ++ "linalg/sparse/Backend.cc",
    src_dir ++ "util/Rotation.cc",
    src_dir ++ "util/ObjectHandle.cc",
    src_dir ++ "util/DataType.cc",
    src_dir ++ "util/QhullSphericalTriangulation.cc",
    src_dir ++ "util/Point.cc",
    src_dir ++ "util/KDTree.cc",
    src_dir ++ "util/CGALSphericalTriangulation.cc",
    src_dir ++ "util/GaussianLatitudes.cc",
    src_dir ++ "util/function/MDPI_functions.cc",
    src_dir ++ "util/function/VortexRollup.cc",
    src_dir ++ "util/function/SolidBodyRotation.cc",
    src_dir ++ "util/function/SphericalHarmonic.cc",
    src_dir ++ "util/Geometry.cc",
    src_dir ++ "util/Allocate.cc",
    src_dir ++ "util/Unique.cc",
    src_dir ++ "util/Polygon.cc",
    src_dir ++ "util/Factory.cc",
    src_dir ++ "util/ConvexSphericalPolygon.cc",
    src_dir ++ "util/GridPointsJSONWriter.cc",
    src_dir ++ "util/SphericalPolygon.cc",
    src_dir ++ "util/Object.cc",
    src_dir ++ "util/Checksum.cc",
    src_dir ++ "util/PolygonXY.cc",
    src_dir ++ "util/Metadata.cc",
    src_dir ++ "util/Config.cc",
    src_dir ++ "array/Table.cc",
    src_dir ++ "array/native/NativeMakeView.cc",
    src_dir ++ "array/native/NativeIndexView.cc",
    src_dir ++ "array/native/NativeArrayView.cc",
    src_dir ++ "array/native/NativeArray.cc",
    src_dir ++ "array/SVector.cc",
    src_dir ++ "array/ArrayDataStore.cc",
    src_dir ++ "array/gridtools/GridToolsArray.cc",
    src_dir ++ "array/gridtools/GridToolsMakeView.cc",
    src_dir ++ "array/gridtools/GridToolsIndexView.cc",
    src_dir ++ "array/gridtools/GridToolsArrayView.cc",
    src_dir ++ "array/LocalView.cc",
    src_dir ++ "array/TableView.cc",
    src_dir ++ "array/ArraySpec.cc",
    src_dir ++ "array/Vector.cc",
    src_dir ++ "functionspace/CellColumns.cc",
    src_dir ++ "functionspace/BlockStructuredColumns.cc",
    src_dir ++ "functionspace/StructuredColumns.cc",
    src_dir ++ "functionspace/Spectral.cc",
    src_dir ++ "functionspace/CubedSphereColumns.cc",
    src_dir ++ "functionspace/PointCloud.cc",
    src_dir ++ "functionspace/detail/FunctionSpaceInterface.cc",
    src_dir ++ "functionspace/detail/BlockStructuredColumnsInterface.cc",
    src_dir ++ "functionspace/detail/BlockStructuredColumns.cc",
    src_dir ++ "functionspace/detail/StructuredColumnsInterface.cc",
    src_dir ++ "functionspace/detail/StructuredColumns.cc",
    src_dir ++ "functionspace/detail/StructuredColumns_setup.cc",
    src_dir ++ "functionspace/detail/NodeColumnsInterface.cc",
    src_dir ++ "functionspace/detail/CubedSphereStructure.cc",
    src_dir ++ "functionspace/detail/PointCloudInterface.cc",
    src_dir ++ "functionspace/detail/CellColumnsInterface.cc",
    src_dir ++ "functionspace/detail/SpectralInterface.cc",
    src_dir ++ "functionspace/detail/FunctionSpaceImpl.cc",
    src_dir ++ "functionspace/detail/StructuredColumns_create_remote_index.cc",
    src_dir ++ "functionspace/detail/NodeColumns_FieldStatistics.cc",
    src_dir ++ "functionspace/NodeColumns.cc",
    src_dir ++ "functionspace/FunctionSpace.cc",
    src_dir ++ "functionspace/EdgeColumns.cc",
    src_dir ++ "io/ArrayAdaptor.cc",
    src_dir ++ "runtime/trace/CodeLocation.cc",
    src_dir ++ "runtime/trace/CallStack.cc",
    src_dir ++ "runtime/trace/Barriers.cc",
    src_dir ++ "runtime/trace/Timings.cc",
    src_dir ++ "runtime/trace/Logging.cc",
    src_dir ++ "runtime/trace/Nesting.cc",
    src_dir ++ "runtime/AtlasTool.cc",
    src_dir ++ "runtime/Exception.cc",
    src_dir ++ "runtime/Log.cc",
    src_dir ++ "output/Output.cc",
    src_dir ++ "output/detail/PointCloudIO.cc",
    src_dir ++ "output/detail/GmshIO.cc",
    src_dir ++ "output/detail/GmshImpl.cc",
    src_dir ++ "output/detail/GmshInterface.cc",
    src_dir ++ "output/Gmsh.cc",
    src_dir ++ "library/Plugin.cc",
    src_dir ++ "library/FloatingPointExceptions.cc",
    src_dir ++ "library/Library.cc",
    src_dir ++ "option/Options.cc",
    src_dir ++ "option/TransOptions.cc",
    src_dir ++ "field/FieldSet.cc",
    src_dir ++ "field/State.cc",
    src_dir ++ "field/FieldCreatorIFS.cc",
    src_dir ++ "field/FieldCreatorArraySpec.cc",
    src_dir ++ "field/FieldCreator.cc",
    src_dir ++ "field/detail/FieldInterface.cc",
    src_dir ++ "field/detail/FieldImpl.cc",
    src_dir ++ "field/detail/MissingValue.cc",
    src_dir ++ "field/MissingValue.cc",
    src_dir ++ "field/Field.cc",
    src_dir ++ "numerics/Nabla.cc",
    src_dir ++ "numerics/Method.cc",
    src_dir ++ "numerics/fvm/Nabla.cc",
    src_dir ++ "numerics/fvm/Method.cc",
    src_dir ++ "meshgenerator/detail/RegularMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/CubedSphereMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/MeshGeneratorInterface.cc",
    src_dir ++ "meshgenerator/detail/cubedsphere/CubedSphereUtility.cc",
    src_dir ++ "meshgenerator/detail/MeshGeneratorFactory.cc",
    src_dir ++ "meshgenerator/detail/CubedSphereDualMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/MeshGeneratorImpl.cc",
    src_dir ++ "meshgenerator/detail/DelaunayMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/HealpixMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/StructuredMeshGenerator.cc",
    src_dir ++ "meshgenerator/detail/NodalCubedSphereMeshGenerator.cc",
    src_dir ++ "meshgenerator/MeshGenerator.cc",
    src_dir ++ "trans/VorDivToUV.cc",
    src_dir ++ "trans/ifs/TransIFSNodeColumns.cc",
    src_dir ++ "trans/ifs/LegendreCacheCreatorIFS.cc",
    src_dir ++ "trans/ifs/TransIFSStructuredColumns.cc",
    src_dir ++ "trans/ifs/VorDivToUVIFS.cc",
    src_dir ++ "trans/ifs/TransIFS.cc",
    src_dir ++ "trans/Trans.cc",
    src_dir ++ "trans/local/TransLocal.cc",
    src_dir ++ "trans/local/LegendreCacheCreatorLocal.cc",
    src_dir ++ "trans/local/LegendrePolynomials.cc",
    src_dir ++ "trans/local/VorDivToUVLocal.cc",
    src_dir ++ "trans/detail/TransImpl.cc",
    src_dir ++ "trans/detail/TransFactory.cc",
    src_dir ++ "trans/detail/TransInterface.cc",
    src_dir ++ "trans/Cache.cc",
    src_dir ++ "trans/LegendreCacheCreator.cc",
    src_dir ++ "domain/detail/RectangularDomain.cc",
    src_dir ++ "domain/detail/DomainFactory.cc",
    src_dir ++ "domain/detail/EmptyDomain.cc",
    src_dir ++ "domain/detail/Domain.cc",
    src_dir ++ "domain/detail/ZonalBandDomain.cc",
    src_dir ++ "domain/detail/GlobalDomain.cc",
    src_dir ++ "domain/Domain.cc",
    src_dir ++ "interpolation/Vector2D.cc",
    src_dir ++ "interpolation/Vector3D.cc",
    src_dir ++ "interpolation/element/Quad3D.cc",
    src_dir ++ "interpolation/element/Quad2D.cc",
    src_dir ++ "interpolation/element/Triag3D.cc",
    src_dir ++ "interpolation/element/Triag2D.cc",
    src_dir ++ "interpolation/Cache.cc",
    src_dir ++ "interpolation/NonLinear.cc",
    src_dir ++ "interpolation/Interpolation.cc",
    src_dir ++ "interpolation/method/knn/GridBoxAverage.cc",
    src_dir ++ "interpolation/method/knn/GridBox.cc",
    src_dir ++ "interpolation/method/knn/NearestNeighbour.cc",
    src_dir ++ "interpolation/method/knn/GridBoxMaximum.cc",
    src_dir ++ "interpolation/method/knn/KNearestNeighboursBase.cc",
    src_dir ++ "interpolation/method/knn/KNearestNeighbours.cc",
    src_dir ++ "interpolation/method/knn/GridBoxMethod.cc",
    src_dir ++ "interpolation/method/Intersect.cc",
    src_dir ++ "interpolation/method/Method.cc",
    src_dir ++ "interpolation/method/cubedsphere/CellFinder.cc",
    src_dir ++ "interpolation/method/cubedsphere/CubedSphereBilinear.cc",
    src_dir ++ "interpolation/method/PointIndex2.cc",
    src_dir ++ "interpolation/method/structured/kernels/QuasiCubic3DKernel.cc",
    src_dir ++ "interpolation/method/structured/Linear2D.cc",
    src_dir ++ "interpolation/method/structured/Linear3D.cc",
    src_dir ++ "interpolation/method/structured/QuasiCubic3D.cc",
    src_dir ++ "interpolation/method/structured/QuasiCubic2D.cc",
    src_dir ++ "interpolation/method/structured/Cubic2D.cc",
    src_dir ++ "interpolation/method/structured/Cubic3D.cc",
    src_dir ++ "interpolation/method/PointIndex3.cc",
    src_dir ++ "interpolation/method/MethodFactory.cc",
    src_dir ++ "interpolation/method/Ray.cc",
    src_dir ++ "interpolation/method/unstructured/FiniteElement.cc",
    src_dir ++ "interpolation/method/unstructured/UnstructuredBilinearLonLat.cc",
    src_dir ++ "interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.cc",
    src_dir ++ "interpolation/method/PointSet.cc",
    src_dir ++ "interpolation/method/sphericalvector/SphericalVector.cc",
    src_dir ++ "interpolation/nonlinear/NonLinear.cc",
    src_dir ++ "interpolation/nonlinear/Missing.cc",
    src_dir ++ "projection/Projection.cc",
    src_dir ++ "projection/detail/LonLatProjection.cc",
    src_dir ++ "projection/detail/LambertConformalConicProjection.cc",
    src_dir ++ "projection/detail/MercatorProjection.cc",
    src_dir ++ "projection/detail/SchmidtProjection.cc",
    src_dir ++ "projection/detail/ProjectionImpl.cc",
    src_dir ++ "projection/detail/CubedSphereProjectionBase.cc",
    src_dir ++ "projection/detail/ProjProjection.cc",
    src_dir ++ "projection/detail/VariableResolutionProjection.cc",
    src_dir ++ "projection/detail/LambertAzimuthalEqualAreaProjection.cc",
    src_dir ++ "projection/detail/ProjectionFactory.cc",
    src_dir ++ "projection/detail/CubedSphereEquiDistProjection.cc",
    src_dir ++ "projection/detail/CubedSphereEquiAnglProjection.cc",
    src_dir ++ "grid/StructuredGrid.cc",
    src_dir ++ "grid/StructuredPartitionPolygon.cc",
    src_dir ++ "grid/Iterator.cc",
    src_dir ++ "grid/SpecRegistry.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N576.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N16.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N80.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N1280.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N640.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N1024.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N32.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N512.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N48.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N4000.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N160.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N2000.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N1600.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N256.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N200.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/PointsPerLatitude.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N320.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N8000.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N800.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N400.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N64.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N24.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N96.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N128.cc",
    src_dir ++ "grid/detail/pl/classic_gaussian/N.cc",
    src_dir ++ "grid/detail/partitioner/EqualAreaPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingMeshPartitionerSphericalPolygon.cc",
    src_dir ++ "grid/detail/partitioner/EqualRegionsPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingMeshPartitionerBruteForce.cc",
    src_dir ++ "grid/detail/partitioner/SerialPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingFunctionSpacePartitioner.cc",
    src_dir ++ "grid/detail/partitioner/CheckerboardPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/EqualBandsPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingMeshPartitionerLonLatPolygon.cc",
    src_dir ++ "grid/detail/partitioner/BandsPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingFunctionSpacePartitionerLonLatPolygon.cc",
    src_dir ++ "grid/detail/partitioner/MatchingMeshPartitionerCubedSphere.cc",
    src_dir ++ "grid/detail/partitioner/TransPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/CubedSpherePartitioner.cc",
    src_dir ++ "grid/detail/partitioner/MatchingMeshPartitioner.cc",
    src_dir ++ "grid/detail/partitioner/Partitioner.cc",
    src_dir ++ "grid/detail/partitioner/RegularBandsPartitioner.cc",
    src_dir ++ "grid/detail/distribution/DistributionFunction.cc",
    src_dir ++ "grid/detail/distribution/DistributionImpl.cc",
    src_dir ++ "grid/detail/distribution/DistributionArray.cc",
    src_dir ++ "grid/detail/distribution/SerialDistribution.cc",
    src_dir ++ "grid/detail/distribution/BandsDistribution.cc",
    src_dir ++ "grid/detail/tiles/TilesFactory.cc",
    src_dir ++ "grid/detail/tiles/LFRicTiles.cc",
    src_dir ++ "grid/detail/tiles/Tiles.cc",
    src_dir ++ "grid/detail/tiles/FV3Tiles.cc",
    src_dir ++ "grid/detail/spacing/LinearSpacing.cc",
    src_dir ++ "grid/detail/spacing/SpacingFactory.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N576.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N16.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N80.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N1280.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N640.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N1024.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N32.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N512.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N48.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N4000.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N160.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N2000.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N1600.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N256.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N200.cc",
    src_dir ++ "grid/detail/spacing/gaussian/Latitudes.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N320.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N8000.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N800.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N400.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N64.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N24.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N96.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N128.cc",
    src_dir ++ "grid/detail/spacing/gaussian/N.cc",
    src_dir ++ "grid/detail/spacing/GaussianSpacing.cc",
    src_dir ++ "grid/detail/spacing/FocusSpacing.cc",
    src_dir ++ "grid/detail/spacing/Spacing.cc",
    src_dir ++ "grid/detail/spacing/CustomSpacing.cc",
    src_dir ++ "grid/detail/vertical/VerticalInterface.cc",
    src_dir ++ "grid/detail/grid/RegionalVariableResolution.cc",
    src_dir ++ "grid/detail/grid/Gaussian.cc",
    src_dir ++ "grid/detail/grid/CubedSphere.cc",
    src_dir ++ "grid/detail/grid/GridFactory.cc",
    src_dir ++ "grid/detail/grid/Healpix.cc",
    src_dir ++ "grid/detail/grid/Structured.cc",
    src_dir ++ "grid/detail/grid/Unstructured.cc",
    src_dir ++ "grid/detail/grid/Regional.cc",
    src_dir ++ "grid/detail/grid/LonLat.cc",
    src_dir ++ "grid/detail/grid/GridBuilder.cc",
    src_dir ++ "grid/detail/grid/Grid.cc",
    src_dir ++ "grid/Tiles.cc",
    src_dir ++ "grid/Distribution.cc",
    src_dir ++ "grid/Grid.cc",
    src_dir ++ "grid/Spacing.cc",
    src_dir ++ "grid/Vertical.cc",
    src_dir ++ "grid/CubedSphereGrid.cc",
    src_dir ++ "grid/Partitioner.cc",
    src_dir ++ "grid/StencilComputer.cc",
    src_dir ++ "grid/UnstructuredGrid.cc",
};
